config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pages do
    get 'user_home', on: :collection
    post 'search', on: :collection
    get 'search_history', on: :collection
  end
  root 'pages#index'

end

app/models/searched_artist.rb
class SearchedArtist < ActiveRecord::Base


	def self.getArtistInfo(artist)
		artist_info_req=HTTParty.get("http://ws.audioscrobbler.com/2.0/?method=artist.getinfo&artist=#{artist}&api_key=a94b06e62d0e1cfecfe3010e5cc0b790&format=json")
		top_tracks_req=HTTParty.get("http://ws.audioscrobbler.com/2.0/?method=artist.gettoptracks&artist=#{artist}&api_key=a94b06e62d0e1cfecfe3010e5cc0b790&format=json")
		artist_info={}
		if artist_info_req.parsed_response["error"].nil?	
			artist_info["name"]=artist_info_req.parsed_response["artist"]["name"]
			artist_info["url"]=artist_info_req.parsed_response["artist"]["url"]
			artist_info["bio"]=artist_info_req.parsed_response["artist"]["bio"]["summary"]
			top_tracks=[]
			top_tracks_req.parsed_response["toptracks"]["track"].each do |track|
				tracks={}
				tracks["name"]=track["name"]
				tracks["url"]=track["url"]
				top_tracks<<tracks
			end
		else
			error_info=artists_info_req.parsed_response["message"]
		end
		return artist_info, top_tracks, error_info
	end

	def self.getSimilarArtists(artist)
		similar_artists_array=[]
		similar_artists_req=HTTParty.get("http://ws.audioscrobbler.com/2.0/?method=artist.getSimilar&artist=#{artist}&api_key=a94b06e62d0e1cfecfe3010e5cc0b790&format=json")
		if similar_artists_req.parsed_response["error"].present?
			error=similar_artists_req.parsed_response["message"]
		elsif similar_artists_req.parsed_response["similarartists"]["artist"].kind_of?(Array)
			similar_artists_req.parsed_response["similarartists"]["artist"].each do |artist|
				similar_artists={}
				similar_artists["name"]=artist["name"]
				similar_artists["url"]=artist["url"]
				similar_artists_array<<similar_artists
			end
		else
			error="No Results Found."
		end
		return error,similar_artists_array
	end

	def self.getSearchedArtists(id)
		searched_artists=[]
		temp=SearchedArtist.where(user_id: id)
		temp.each do |artist|
			searched_artists<<artist.artist_name
		end
		searched_artists
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
 	user_home_pages_path
  end

  def after_sign_up_path_for(resource)
 	user_home_pages_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	
	before_action :authenticate_user!, except: [:index]

	def search
		artist=params["search"]
		user_id=current_user.id
		dup_count=SearchedArtist.where(artist_name: artist).count
		if dup_count==0
			new_row=SearchedArtist.create user_id: user_id, artist_name: artist
		end
		@artist_info, @top_tracks, @error_info=SearchedArtist.getArtistInfo(artist)
		@error,@similar_artists=SearchedArtist.getSimilarArtists(artist)
		render 'user_home'
	end 

	def search_history
		@searched_artists=SearchedArtist.getSearchedArtists(current_user.id)
		render 'user_home'
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lastfmapi</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/_header.html.erb
<header id="header" style="display: initial">
	<h1><a href="/">Muse</a></h1>
	<nav id="nav">
		<ul>
			<% if current_user %>
				<li><a href="/pages/user_home" method="get">APP</a></li>
				<li><%= link_to "HISTORY", search_history_pages_path, method: 'get' %></li>
				<li><%= link_to "LOG OUT", destroy_user_session_path,method: 'delete' %></li>
			<% else %>
				<li><a href="/">HOME</a></li>
				<li><a href="/users/sign_in">LOGIN</a></li>
				<li><a href="/users/sign_up">SIGNUP</a></li>
			<% end %>
		</ul>
	</nav>
</header>

app/views/pages/index.html.erb
<body class="landing">

	<!-- Header -->
		<%= render partial: "header" %>

	<!-- Banner -->
		<section id="banner">
			<h2>This is MUSE</h2>
			<p>A Music Recommendation App.</p>
			<ul class="actions">
				<li>
					<a href="#one" class="button big">Learn More</a>
				</li>
			</ul>
		</section>

	<!-- One -->
		<section id="one" class="wrapper style1 align-center">
			<div class="container">
				<header>
					<h2>Welcome to MUSE</h2>
					<p>A new generation music recommendation system.</p>
				</header>
				<div class="row 200%">
					<section class="4u 12u$(small)">
						<i class="icon big rounded fa-user"></i>
						<p>SignUp today to explore the new era of music, your era. Get ready to get MUSIC-struck.</p>
					</section>
					<section class="4u 12u$(small)">
						<i class="icon big rounded fa-search"></i>
						<p>Search for your favourite music artist and get the information and our recommendations.</p>
					</section>
					<section class="4u$ 12u$(small)">
						<i class="icon big rounded fa-clock-o"></i>
						<p>Our recommendation system works round the clock. So, get ready to listen to your favourite music whenever you want.</p>
					</section>
				</div>
			</div>
		</section>

	<!-- Two -->
		<section id="two" class="wrapper style2 align-center">
			<div class="container">
				<header>
					<h2>Well, Here you are.</h2>
					<p>While thee have travelled thus far, here are few more reasons to start right NOW.</p>
				</header>
				<div class="row">
					<section class="feature 6u 12u$(small)">
						<img class="image fit" src="/assets/pic02.jpg" alt="" />
						<h3 class="title">Leave Books, Get Muse.</h3>
						<p>Do not search the books for the information of your favourite artists. Just type it and get all the information of that artist as well as other artists like him.</p>
					</section>
					<section class="feature 6u$ 12u$(small)">
						<img class="image fit" src="/assets/pic04.jpg" alt="" />
						<h3 class="title">Travel, Listen, Enjoy</h3>
						<p>Get to know the kind of music you would love with our great recommendation system and have fun when travelling while listening to YOUR music.</p>
					</section>
				</div>
			</div>
		</section>

	<!-- Footer -->
		<footer id="footer">
			<div class="container">
				<div class="row">
					
					<section class="4u 6u(medium) 12u$(small)">
						<h3>Share</h3>
						<p>Share our app to help other people who are deprived of good music find what they need.</p>
					</section>
					<section class="4u 6u$(medium) 12u$(small)">
						<h3>Any help ? </h3>
						<p>Please feel free to contact us anytime. We will get back to you as soon as possible.</p>
					</section>
					<section class="4u$ 12u$(medium) 12u$(small)">
						<h3>Contact Us</h3>
						<ul class="icons">
							<li><a href="#" class="icon rounded fa-twitter"><span class="label">Twitter</span></a></li>
							<li><a href="#" class="icon rounded fa-facebook"><span class="label">Facebook</span></a></li>
							<li><a href="#" class="icon rounded fa-google-plus"><span class="label">Google+</span></a></li>
						</ul>
						<ul class="tabular">
							<li>
								<h3>Address</h3>
								1234 Kormangala<br>
								Bangalore, Karnatake - 567005
							</li>
							<li>
								<h3>Mail</h3>
								<a href="#">help@muse.com</a>
							</li>
							<li>
								<h3>Phone</h3>
								+91-9788963738
							</li>
						</ul>
					</section>
				</div>
			</div>
		</footer>

</body>

app/views/pages/user_home.html.erb
<style>
#search-form{
	width:60%;
	margin-left: 25%;
	margin-top: 5rem;
}
#search{
	width:30rem;
	float:left;
}
.text{
	font-weight: bold !important;
	font-family: LatoLight;
	color: #696969 !important;
	display:inline !important;
}
#content{
	width: 70%;
	margin-left: 15%;
}
</style>
<div id="header">
	<%= render partial: "header" %>
</div>
<div id="search-form">
	<%= form_tag search_pages_path, :method => 'post' do %>
	  <p>
	    <%= text_field_tag :search, nil, placeholder: "Search your favourite artist" %>
	    <%= submit_tag "Search" %>
	  </p>
	<% end %>
</div>
<div id="content">
	<div class="row">
		<div id="artist-info" class="col-md-6">
			<% if @error_info.blank? %>
				<% if @artist_info %>
					<div class="text">Name: </div><a href="<%= @artist_info['url'] %>"><%= @artist_info["name"] %></a><br />
					<div class="text">Summary: </div><div id="summary"><%= @artist_info["bio"].html_safe %></div>
				<% end %>
				<br />
				<% if @top_tracks %>
					<div class="text">Top Tracks: </div><br /><br />
					<ul>
						<% @top_tracks.each do |track| %>
							<li><a href="<%= track['url'] %>"><%= track["name"] %> </a></li><br />
						<% end %>
					</ul>
				<% end %>
			<% end %>
		</div>
		<div id="related-artists" class="col-md-6">
			<% if @error.present? %>
				<div class="text">SIMILAR ARTISTS:</div><br /><br />
				<%= @error %>
			<% elsif @similar_artists %>
				<div class="text">SIMILAR ARTISTS:</div><br /><br />
				<ul>
					<% @similar_artists.in_groups_of(5, false).each do |group| %>
						<div class="row">
							<% group.each do |artist| %>
								<div class="col-md-4">
									<div class="artist">
										<li><a href="<%= artist['url'] %>"><%= artist["name"] %> </a></li>
									</div>
								</div>
							<% end %>
						</div>
						<br />
					<% end %>
				</ul>
			<% end %>
		</div>
	</div>
	<div class='row'>
		<div id="search-history">
			<% if @searched_artists %>
				<div class="text">SEARCHED ARTISTS' NAMES:</div><br /><br />
				<ul>
					<% @searched_artists.each do |artist| %>
						<li><%= artist %></li><br />
					<% end %>
				</ul>
			<% end %>
		</div>
	</div>
</div>